# Generated by Django 4.0.6 on 2022-08-08 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='app_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser'),
        ),
    ]
