# Generated by Django 4.1 on 2022-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_template_app_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
