# Generated by Django 4.1 on 2022-08-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='appuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
