# Generated by Django 4.1 on 2022-08-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_first_name_appuser_last_name_appuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='auth_code',
            field=models.TextField(default='null'),
        ),
    ]
